### ISSUE TITLE
vignette detailing general guidance for using covariates...

### ISSUE THREAD

**Issue by adw96** [adw96/DivNet#106]
... in `DivNet` and `betta()` would be very useful!

**Comment by ejwatson** [comment]
This would be useful! I have two specific questions related to covariates for DivNet and betta. It's probably easiest to explain it in the context of my research questions.

I'm testing two similar hypotheses:
- The first betta model tests the effect of maternal depression during pregnancy on (human) infant GM diversity, adjusting for a measure of socioeconomic status. 
- The second betta model tests the effect of maternal perceived stress during pregnancy on infant GM diversity, also adjusting for socioeconomic status. 

**First question:**  Do the covariates in DivNet and the betta model need to be the same? I'm excluding infants who received antibiotics, were birthed via C-section, or reported recent illness, so those variables aren't of concern. However, infant feeding status (breastfeeding vs formula) is a strong predictor of infant GM diversity. Since formula feeding doesn't confound (it may rather partially mediate...) the relationship between depression/stress during pregnancy and infant GM diversity, I don't think it's necessary to adjust for it the betta hypothesis testing model. But, it's a strong predictor of GM diversity, so should I include it in the DivNet models to estimate Shannon diversity? Perhaps it would increase precision?

**Second question:** Should I run two separate DivNet models for each hypothesis to be tested using betta? (The first DivNet model with depression and the second with perceived stress instead, with SES (and possibly infant feeding) as a covariate in both)

**Comment by ailurophilia** [comment]
Hi @ejwatson – I think it would be helpful to have a little more information here. Do you have technical replicate observations? If not, the simplest approach may be to use breakaway to estimate diversity in each sample and then use `breakaway::betta` to run your regression. If you do have technical replicates, I'd recommend using DivNet with a design matrix that groups technical replicates from the same specimen together (but doesn't include any other covariates). There's an example of how to do this in the DivNet beta diversity vignette.

**Comment by adw96** [comment]
Feel free to reopen @ejwatson, but closing since we haven't heard from you in a while 🙂
