### ISSUE TITLE
Relationship between Bray-Curtis distance and Shannon div estimates

### ISSUE THREAD

**Issue by cyklee** [adw96/DivNet#13]
Hi Amy,

I hope this is an appropriate place to raise a question regarding the vignette.

In the DivNet vignette, it said:

> For glassy and water samples, the estimated diversity is in the middle of the individual diversity estimates, while for altered samples the estimated diversity is lower. That's because the **water and glassy samples are much more similar to each other in terms of relative abundances than the altered samples**, as we can see from the distribution of Bray-Curtis distances between the samples

However, in the estimates of Bray-Curtis distance plot below, glassy.water interaction showed the most distance, while altered.altered showed the least distance. Doesn't that indicate exactly the opposite to the statement above i.e. altered samples are quite similar to each other while glassy vs. water are quite different? Unless you meant glassy.glassy and water.water are quite similar, but those comparisons were not shown.

If possible, could you please clarify the relationship between similarity between samples (Bray-Curtis distance) and the resulting estimated Shannon diversity?

Thank you for all the hard work into DivNet and I am eager to implement it into my future projects!

Kevin

**Comment by adw96** [comment]
Hi Kevin -- thanks for your question. This is exactly the right place to ask.

DivNet works by comparing ecosystems, not comparing samples. While all literature on estimating BC distances to date has focused on samples, focusing on ecosystems allows you to make larger claims about the environment -- claims that are meaningful outside of your study. This makes hypothesis testing valid (previously it wasn't). As a result, DivNet estimates the BC distance between glassy samples and glassy samples as zero (hence not shown). At the ecosystem level, all glassy basalts are the same. Said another way, if you care about differences within the same type of ecosystem, DivNet isn't the right tool for this. DivNet's advantage is in comparing across ecosystems. So rather than doing PERMANOVA to test beta diversity between samples of different types, DivNet allows you to test for a difference directly. So you'd test if altered samples are more like glassy samples than than water samples, but you wouldn't test if altered samples are the same (you tell DivNet they're replicates with x = "char").

Hope that helps!

Amy

**Comment by cyklee** [comment]
Thanks for the speedy reply Amy. I think I'm getting tripped up by the wordings in the vignette example:

> water and glassy samples are much more similar to each other in terms of relative abundances than the altered samples.

Does that mean either:

1. `water.glassy` have lower BC distances compared to `water.altered` or `glassy.altered`.
2. `water.water` & `glassy.glassy` have lower distribution of BC distances compared to `altered.altered`.

... and as a result `water` and `glassy` have higher estimated Shannon diversity than `altered`?

I'm pretty sure I'm misinterpreting it here but I can't see a better alternative interpretation. I'm trying to connect Figure 2 (Shannon diversity estimate) with Figure 3 (Estimate Bray-Curtis distance), so I have a better grasp on between group BC distance and how that would impact the estimated diversity when using DivNet.

Cheers,

Kevin
