### ISSUE TITLE
Partial divnet() and Hypothesis Testing with a Random Effect (and Potentially an Interaction)

### ISSUE THREAD

**Issue by liisaveerus** [adw96/DivNet#31]
Hi,

First of all, a big thank you and a bow for maintaining such amazing packages as breakaway and DivNet.

I have a two-part question, however. Firstly, if I am only interested in estimating Shannon's and Simpson's diversities, is there a way to do that with the divnet() function? Currently, it is taking me too long to calculate all the estimates and it mostly errors due to memory overload.

Secondly, if I wanted to carry out some hypothesis testing with these estimates, what would be the function command for that? I want to test the estimate with an interaction (is that even possible?) and a random effect, i.e. Shannon ~ Organ*Health.Status + (1|Individual.ID).

Thanks so much for your time!

Liisa

**Comment by adw96** [comment]
Hi Liisa! I'm thrilled you find our packages helpful 😸 

1. Unfortunately the big overhead with running `divnet` is fitting the model. Therefore, even if you only want to estimate Shannon and Simpson diversity (and not the beta-diversity indices), you don't save any time compared to estimating all of them. 

How many taxa do you have? We are chatting with another user about computation time; see #32 

2. Hypothesis testing with both interactions and random effects are very possible! Essentially you take the estimates that you get from `DivNet` and use them in the function `betta_random` in our package `breakaway`. Unfortunately the interface to `breakaway::betta_random` is a bit tedious, so I plan to add a vignette on this later today (or soon!). I will post the link here when it's done. In the meantime, after `library(breakaway)`, you can get the documentation for this function with `?betta_random`. Make sure to `devtools::install_github("adw96/breakaway")` rather than downloading it from CRAN. 

More soon on random effects with DivNet!

**Comment by adw96** [comment]
Hi Liisa -- I just made a new vignette in breakaway that talks through fixed and random effects models for diversity. It includes both species richness (estimated using breakaway) and Shannon and Simpson diversity (estimated using DivNet).

Check out the vignette here:

https://github.com/adw96/breakaway/blob/master/vignettes/diversity-hypothesis-testing.Rmd

You can definitely fit an interaction model, e.g., with something like
```
betta_random(chats = combined_shannon$estimate,
                                       ses = combined_shannon$error,
                                       X = model.matrix(~Organ*Health.Status, data = combined_shannon),
                                       groups=combined_shannon$Individual) 
```

😸

**Comment by liisaveerus** [comment]
Thank you so much, Amy, this has been really helpful! 

For other users, my data set is 350 samples * 7100 ASVs. Still struggling to get divnet() to work due to memory overload, but attempting to run this on a server.

The betta_random() works like a charm, according to your shared vignette. Just one question about the output.

results <- betta_random(chats = estimated_richness$estimate,
                                       ses = estimated_richness$error,
                                       X = model.matrix(~Organ*Health.Status, data = estimated_richness),
                                       groups=estimated_richness$Individual.ID) 

For clarification:
Organ: heart, liver, lung, kidney
Health.Status: healthy, symptomatic

<img width="411" alt="Example" src="https://user-images.githubusercontent.com/52078155/63431117-11e42600-c416-11e9-88f3-c91f06413e5d.PNG">

Are the first estimates for healthy organs and then the Health.Status:Symptomatic is for heart*symptomatic?

Thanks again!

**Comment by adw96** [comment]
For future readers -- The specific interpretation has now been answered in #34
