### ISSUE TITLE
Converting to Exponential Shannon

### ISSUE THREAD

**Issue by ianartmor** [adw96/DivNet#43]
Hi,

Apologies in advance for the mathematically-ignorant question.

To convert to exponential Shannon estimates, can I just do exp(estimate) and exp(error)? Or does exponential Shannon need to be estimated from the beginning to properly estimate error?

Thanks,
Ian

**Comment by adw96** [comment]
Great question -- and great intuition regarding propagating errors. You can do exp(estimate) to get a the maximum likelihood estimate of exponential Shannon (monotone transformations of MLEs are maximum likelihood estimates of the transformed variable). 

The error in this transformed estimate is a little trickier. I would say that using the delta method is a reasonable choice. I just did the math for you, and you can get the standard error in exp(Shannon) as 

standard error in exp(Shannon) = standard error in Shannon  multiplied by exp(Shannon estimate).

So essentially instead of exp(error) you want "error x exp(estimate)". 

Hope that helps!

**Comment by adw96** [comment]
Post script for myself later -- we want Var(f(a)) where f(a) = exp(a) so df/da = exp(a). So
Var in f(a-hat) \approx Var(a-hat) \times (df/da)^2, where the derivative is evaluated at a-hat
so 
std error (f(a-hat)) = std error (a-hat) \times exp(a-hat).

**Comment by ianartmor** [comment]
That definitely helps; thank you so much!
